export const SELECT_MULTI_FILE = "SELECT_MULTI_FILE";
export const SELECT_SINGLE_FILE = "SELECT_SINGLE_FILE";
export const SELECT_FILE_ERROR_SIZE = "SELECT_FILE_ERROR_SIZE";
export const SELECT_FILE_ERROR_TYPE = "SELECT_FILE_ERROR_TYPE";
export const REFRESH_ERROR = "REFRESH_ERROR";
export const SET_FILE_LIST = "SET_FILE_LIST";
export const DELETE_MULTI_FILE = "DELETE_MULTI_FILE";
export const DELETE_SINGLE_FILE = "DELETE_SINGLE_FILE";
